language: python

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-matplotlib python-numpy

virtualenv:
    system_site_packages: true

install:
    - pip install -e . --use-mirrors 

python:
    - "2.7"

script:
  - rm -rf my_project
  - pyak47-newproject my_project
  - pyak47-run my_project
