language: python

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-matplotlib python-numpy

virtualenv:
	system_site_packages: true


install:
    - pip install -e . --use-mirrors 

python:
    - "2.6"
    - "2.7"

script:
  - rm -rf my_project
  - multimech-newproject my_project
  - multimech-run my_project
