language: python

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-matplotlib python-numpy
    - version_short=`python --version 2>&1|sed "s/.*\ \(.*\)\.[0-9]$/\1/"`; find  /usr/share/pyshared/ -maxdepth 1 -print0 | xargs -I{} -0 ln -s {} /home/travis/virtualenv/python$version_short/lib/python$version_short/site-packages/; ls /home/travis/virtualenv/python$version_short/lib/python$version_short/site-packages/

install:
    - pip install -e . --use-mirrors 

python:
    - "2.6"
    - "2.7"

script:
  - rm -rf my_project
  - multimech-newproject my_project
  - multimech-run my_project
