language: python

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-matplotlib python-numpy
    - python --version 2>&1|sed "s/.*\ \(.*\)\.[0-9]$/\1/"
    - version_short=`python --version 2>&1|sed "s/.*\ \(.*\)\.[0-9]$/\1/"`; ln -s /usr/share/pyshared/matplotlib /home/travis/virtualenv/python$version_short/lib/python$version_short/site-packages/matplotlib
    - version_short=`python --version 2>&1|sed "s/.*\ \(.*\)\.[0-9]$/\1/"`; ln -s /usr/share/pyshared/numpy /home/travis/virtualenv/python$version_short/lib/python$version_short/site-packages/numpy

install:
    - pip install -e . --use-mirrors 

python:
    - "2.6"
    - "2.7"

script:
  - rm -rf my_project
  - multimech-newproject my_project
  - multimech-run my_project
